# Generated by Django 2.1.3 on 2018-12-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='my_app.Shelter'),
        ),
    ]
