# Generated by Django 2.1.3 on 2018-12-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_shelter_shelter_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='shelter_logo',
            field=models.ImageField(blank=True, null=True, upload_to='my_app/media/my_app'),
        ),
    ]
