# Generated by Django 2.1.3 on 2018-12-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20181219_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='dog_logo',
            field=models.ImageField(blank=True, null=True, upload_to='my_app/dogs'),
        ),
    ]
